/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {
        Squirrel rootSquirrel = new Squirrel("sandy");
        Node nodeOne = new Node(rootSquirrel);


        Squirrel squeaks = new Squirrel("squeaks");
        Node nodeTwo = new Node(squeaks);

        Squirrel fluffybutt = new Squirrel("Mr. Fluffy Butt");
        Node nodeThree = new Node(fluffybutt);
 
        nodeOne.setLeft(nodeTwo);
        nodeOne.setRight(nodeThree);
 
        Node retrievedLeft = nodeOne.left(); // This should retrieve the left node
        Node retrievedRight = nodeOne.right(); // This should retrieve the right node 
        System.out.println("Root: " + nodeOne.getData().getName());
        System.out.println("Raw root name: " + rootSquirrel.getName());
        System.out.println("Left child: " + retrievedLeft.getData().getName());
        System.out.println("Right child: " + retrievedRight.getData().getName());
    }

   

}
